# Generated by Django 2.0.9 on 2019-01-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=60)),
                ('Injury', models.CharField(max_length=60)),
                ('Acute_plan_checklist', models.TextField()),
                ('Acute_plan_reasons', models.TextField()),
                ('Follow_up', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
